version: '3.4'

services:


  globoticket.web:
    image: ${DOCKER_REGISTRY-}globoticketweb
    build:
      context: .
      dockerfile: GloboTicket.Client/Dockerfile
    depends_on:
      - globoticket.services.discount
      - globoticket.services.eventcatalog
      - globoticket.services.shoppingbasket
      - globoticket.services.ordering
      - globoticket.services.marketing
      - globoticket.services.payment


  globoticket.services.discount:
    image: ${DOCKER_REGISTRY-}globoticketservicesdiscount
    build:
      context: .
      dockerfile: GloboTicket.Services.Discount/Dockerfile


  globoticket.services.eventcatalog:
    image: ${DOCKER_REGISTRY-}globoticketserviceseventcatalog
    build:
      context: .
      dockerfile: GloboTicket.Services.EventCatalog/Dockerfile


  globoticket.services.shoppingbasket:
    image: ${DOCKER_REGISTRY-}globoticketservicesshoppingbasket
    build:
      context: .
      dockerfile: GloboTicket.Services.ShoppingBasket/Dockerfile
    depends_on:
      - globoticket.services.discount
      - globoticket.services.eventcatalog


  globoticket.services.ordering:
    image: ${DOCKER_REGISTRY-}globoticketservicesordering
    build:
      context: .
      dockerfile: GloboTicket.Services.Order/Dockerfile


  globoticket.services.marketing:
    image: ${DOCKER_REGISTRY-}globoticketservicesmarketing
    build:
      context: .
      dockerfile: GloboTicket.Services.Marketing/Dockerfile
    depends_on:
      - globoticket.services.shoppingbasket


  globoticket.services.payment:
    image: ${DOCKER_REGISTRY-}globoticketservicespayment
    build:
      context: .
      dockerfile: GloboTicket.Services.Payment/Dockerfile
    depends_on:
      - external.paymentgateway


  external.paymentgateway:
    image: ${DOCKER_REGISTRY-}externalpaymentgateway
    build:
      context: .
      dockerfile: External.PaymentGateway/Dockerfile

